# Local Development Overrides
version: '3'

services:
  app:
    environment:
      - XDEBUG_ENABLE=true
      - XDEBUG_REMOTE_PORT=9001
      - XDEBUG_IDE_KEY=PHPSTORM
      - XDEBUG_REMOTE_HOST=host.docker.internal
    ports:
      - "9000:9000"
  web:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
  db:
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret




