version: '3'

networks:
  # TODO - replace with app name
  app:
    driver: "bridge"

volumes:
  mysqldata:
    driver: "local"

services:
  app:
    image: szainmehdi/php:7.4-dev
    container_name: app
    working_dir: /var/www
    environment:
      - XDEBUG_ENABLE=true
      - XDEBUG_REMOTE_PORT=9001
      - XDEBUG_IDE_KEY=PHPSTORM
      - XDEBUG_REMOTE_HOST=host.docker.internal
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - app
    depends_on:
      - db
  web:
    image: nginx:stable-alpine
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - app
  cache:
    image: redis:alpine
    container_name: cache
    networks:
      - app
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app




