version: '3'

networks:
  # TODO - replace with app name
  app:

services:
  php:
    image: szainmehdi/php:7.4-dev
    container_name: php
    working_dir: /var/www
    env_file: ./src/.env
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - app
    depends_on:
      - mysql
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx/logs:/var/log/nginx
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - app
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app



