version: '3'

networks:
  app:
    driver: "bridge"

volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"

services:
  app:
    image: szainmehdi/php:7.4-dev
    container_name: app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app
    depends_on:
      - db
  node:
    image: szainmehdi/node:12.10
    container_name: node
    networks:
      - app
    working_dir: /var/www
    volumes:
      - .:/var/www
  web:
    image: nginx:stable-alpine
    container_name: web
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/certs:/etc/nginx/certs
    depends_on:
      - app
      - db
    networks:
      - app
  cache:
    image: redis:alpine
    container_name: cache
    networks:
      - app
    volumes:
      - redisdata:/data
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app




